"""
app/models/schemas.py
Pydantic schemas and enums defining the ScamShield India data contracts.
"""

from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class InputType(str, Enum):
    PHONE = "PHONE"
    UPI = "UPI"
    URL = "URL"
    BRAND_SEARCH = "BRAND_SEARCH"


class RiskLevel(str, Enum):
    LOW = "LOW"             # Likely authentic / verified official source match
    MEDIUM = "MEDIUM"       # Inconclusive, unverified third-party listing, proceed with caution
    HIGH = "HIGH"           # Multiple conflict signals, unofficial claim, lookalike domain
    CRITICAL = "CRITICAL"   # Direct scam report match, impersonation, verified phishing attempt


class Language(str, Enum):
    EN = "en"  # English
    HI = "hi"  # Hindi
    MR = "mr"  # Marathi


class EvidenceSourceType(str, Enum):
    GOOGLE_SEARCH = "GOOGLE_SEARCH"
    GOOGLE_MAPS = "GOOGLE_MAPS"
    GOOGLE_NEWS = "GOOGLE_NEWS"
    OFFICIAL_SITE = "OFFICIAL_SITE"
    THREAT_FEED = "THREAT_FEED"


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------

class InvestigateRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=3,
        max_length=500,
        description="Raw user input: phone number, UPI ID, website URL, or brand query (e.g. 'SBI customer care')",
        examples=["+91 9876543210", "support@sbi", "https://sbi-helpline-support.in", "SBI customer care helpline"]
    )
    claimed_brand: Optional[str] = Field(
        default=None,
        description="Optional brand name the contact claims to represent (e.g. 'SBI', 'Amazon', 'Airtel')",
        examples=["State Bank of India", "Amazon India", "Paytm"]
    )
    language: Language = Field(
        default=Language.EN,
        description="Target language for the final investigation report"
    )


# ---------------------------------------------------------------------------
# Parsed & Normalized Input Models
# ---------------------------------------------------------------------------

class NormalizedInput(BaseModel):
    raw_query: str
    input_type: InputType
    normalized_value: str
    detected_brand: Optional[str] = None
    
    # Specific attributes extracted depending on input_type
    extracted_domain: Optional[str] = None       # e.g., "sbi-care.in"
    extracted_host: Optional[str] = None
    extracted_vpa_handle: Optional[str] = None   # e.g., "okhicici" from "user@okhicici"
    extracted_phone_e164: Optional[str] = None   # e.g., "+919876543210"


# ---------------------------------------------------------------------------
# Evidence Models
# ---------------------------------------------------------------------------

class EvidenceItem(BaseModel):
    source_type: EvidenceSourceType
    title: str
    snippet: str
    url: Optional[str] = None
    relevance_notes: Optional[str] = None
    timestamp: Optional[str] = None


class SignalBreakdown(BaseModel):
    signal_name: str
    description: str
    score_impact: int
    matched_evidence_urls: List[str] = Field(default_factory=list)


class OfficialContacts(BaseModel):
    display_name: str
    domains: List[str]
    helplines: List[str]
    upi_handles: List[str]
    notes: Optional[str] = None
    source: str = "curated"


# ---------------------------------------------------------------------------
# Final Investigation Output
# ---------------------------------------------------------------------------

class InvestigationReport(BaseModel):
    query: str
    input_type: InputType
    normalized_value: str
    detected_brand: Optional[str] = None
    
    risk_level: RiskLevel
    risk_score: int = Field(ge=0, le=100, description="Risk score from 0 (Safe) to 100 (Extreme Risk)")
    confidence: str = Field(description="'HIGH', 'MEDIUM', or 'LOW' confidence based on evidence quality")
    
    signals: List[SignalBreakdown] = Field(
        default_factory=list,
        description="Audit trail of which rules triggered the score"
    )
    
    evidence: List[EvidenceItem] = Field(
        default_factory=list,
        description="List of raw verified evidence items collected from web/maps/news"
    )
    official_contacts: Optional[OfficialContacts] = None
    warnings: List[str] = Field(default_factory=list)
    
    # Explanations generated by Claude in the chosen language
    summary: str = Field(description="Clear summary of what was found")
    what_was_checked: List[str] = Field(default_factory=list)
    risk_factors: List[str] = Field(default_factory=list)
    unverified_points: List[str] = Field(default_factory=list)
    recommended_actions: List[str] = Field(default_factory=list)
    
    language: Language


class MessageAnalysisRequest(BaseModel):
    message: str = Field(..., min_length=5, max_length=3000)
    language: Language = Language.EN


class MessageAnalysisResponse(BaseModel):
    brand: Optional[str] = None
    scam_type: str
    tactics: List[str] = Field(default_factory=list)
    overall_risk_level: RiskLevel
    overall_risk_score: int = Field(ge=0, le=100)
    reports: List[InvestigationReport] = Field(default_factory=list)